# Generated by Django 3.2.9 on 2021-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211102_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default='No seller', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
