# Generated by Django 3.2.9 on 2021-11-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='User',
            new_name='user',
        ),
    ]
