# Generated by Django 3.2.9 on 2021-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211104_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
