# Generated by Django 3.2.9 on 2021-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_count',
            field=models.IntegerField(default=1),
        ),
    ]
