# Generated by Django 3.2.9 on 2021-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_bid_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
    ]
