# Generated by Django 3.2.9 on 2021-11-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_bid_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='open',
            new_name='active',
        ),
    ]
