# Generated by Django 3.2.9 on 2021-11-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_obtaineditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obtaineditem',
            name='item',
        ),
        migrations.AddField(
            model_name='obtaineditem',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
