# Generated by Django 3.2.9 on 2021-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(default='No title', max_length=50),
            preserve_default=False,
        ),
    ]
