# Generated by Django 3.2.9 on 2021-11-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comment_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtaineditem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
